// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var Unit = { };

var Domain = { };

var Effect = { };

function watch(f, $$event) {
  $$event.watch(f);
  return /* () */0;
}

function map(f, $$event) {
  return $$event.map(f);
}

var $$Event = {
  watch: watch,
  map: map
};

function on($$event, f, store) {
  return store.on($$event, f);
}

function map$1(f, store) {
  return store.map(f);
}

function watch$1(f, store) {
  return store.watch(f);
}

function getState(store) {
  return store.getState();
}

var Store = {
  on: on,
  map: map$1,
  watch: watch$1,
  getState: getState
};

export {
  Unit ,
  Domain ,
  Effect ,
  $$Event ,
  Store ,
  
}
/* No side effect */
