// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";

function dummyFunction(param) {
  return ;
}

function executeSubscription(fn, payload, cleanupFn) {
  var context = function (dispatch) {
    var returnVal = Curry._2(fn, dispatch, payload);
    if (cleanupFn) {
      var fnToExecute = cleanupFn[0];
      return (function (param) {
          Curry._1(fnToExecute, returnVal);
          return ;
        });
    } else {
      return dummyFunction;
    }
  };
  return /* tuple */[
          context,
          payload
        ];
}

function nooperation(dispatch, options) {
  return dispatch(options.action);
}

function noaction(state) {
  return state;
}

export {
  dummyFunction ,
  executeSubscription ,
  nooperation ,
  noaction ,
  
}
/* No side effect */
