// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function batchEffects(payload, effects) {
  return Belt_Array.concatMany([
              [payload],
              effects
            ]);
}

export {
  batchEffects ,
  
}
/* No side effect */
