// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as HyperappUtilJs from "./HyperappUtil.js";

function effects_payload(prim, prim$1) {
  return HyperappUtilJs.flatten(prim, prim$1);
}

function batchEffects(payload, effects) {
  return HyperappUtilJs.flatten(payload, effects);
}

export {
  effects_payload ,
  batchEffects ,
  
}
/* ./HyperappUtil.js Not a pure module */
