// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as HyperappUtilBsJs from "./HyperappUtil.bs.js";

function effects_payload(prim, prim$1) {
  return HyperappUtilBsJs.flatten(prim, prim$1);
}

function batchEffects(payload, effects) {
  return HyperappUtilBsJs.flatten(payload, effects);
}

export {
  effects_payload ,
  batchEffects ,
  
}
/* ./HyperappUtil.bs.js Not a pure module */
