// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/lib/es6/src/jest.js";

Jest.describe("Expect.Operators", (function (param) {
        return Jest.test("==", (function (param) {
                      return Jest.Expect.toBe(3, Jest.Expect.expect(3));
                    }));
      }));

export {
  
}
/*  Not a pure module */
